import { mkdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SRC = path.resolve("src/assets/hero-img.jpg");
const OUT_DIR = path.resolve("public/images");
const WIDTHS = [1280, 1920, 2560];

await mkdir(OUT_DIR, { recursive: true });

const results = [];

for (const width of WIDTHS) {
  const resized = () => sharp(SRC).resize({ width, withoutEnlargement: true });

  const avif = await resized()
    .avif({ quality: 60, effort: 4 })
    .toBuffer();
  const webp = await resized()
    .webp({ quality: 78 })
    .toBuffer();

  const avifName = `hero-${width}.avif`;
  const webpName = `hero-${width}.webp`;

  await Promise.all([
    writeFile(path.join(OUT_DIR, avifName), avif),
    writeFile(path.join(OUT_DIR, webpName), webp),
  ]);

  results.push(
    `${avifName}: ${(avif.length / 1024).toFixed(0)} KB`,
    `${webpName}: ${(webp.length / 1024).toFixed(0)} KB`,
  );
}

const srcSize = (await stat(SRC)).size;
console.log(`Source: hero-img.jpg (${((srcSize ?? 0) / 1024 / 1024).toFixed(2)} MB)`);
for (const line of results) console.log(line);

const placeholder = await sharp(SRC)
  .resize({ width: 64 })
  .blur(1.5)
  .webp({ quality: 60 })
  .toBuffer();

const blurCss = `/* AUTO-GENERATED by scripts/optimize-hero.mjs — do not edit. */
.hero {
  background-image: url("data:image/webp;base64,${placeholder.toString("base64")}");
  background-size: cover;
  background-position: center;
}
`;

const blurCssPath = path.resolve("src/components/hero-blur.css");
await writeFile(blurCssPath, blurCss);
console.log(`hero-blur.css: ${(placeholder.length / 1024).toFixed(1)} KB (inlined placeholder)`);
